### ISSUE TITLE
Create README.

### ISSUE THREAD

**Issue by crocarneiro** [crocarneiro/libstring-utils#2]

**Comment by Knackie** [comment]
HI, i want help, can i ?

**Comment by crocarneiro** [comment]
Hii!

Of course you can. If you want you can create a README with those topics:
* Installation instructions (build from source basically)
* Usage examples (you can get somes in the unity tests)
* Anything else you think you should put into it too

I'm working in a solution to create a .deb package for this automatically, but it won't be ready in time so you can create the README and I'll complement it with the installation instructions from .deb package later.

**Comment by Knackie** [comment]
ok i gonna work on it.
Can you assign me to the repos ?

**Comment by crocarneiro** [comment]
Steps for you:
1. Fork the repo
2. Create README.md
3. Commit
4. Pull Request

Then I'll review and merge your changes

**Comment by Knackie** [comment]
ok thanks you, i gonna do it :)

**Comment by Knackie** [comment]
can you please tag this with hacktoberfest ? 😄

**Comment by crocarneiro** [comment]
I thought even the pull requests in a issue without the tag hacktoberfest were valid to the event. But I can just tag this, no problem.
